spring.application.name=addressbook
spring.datasource.url=jdbc:mysql://localhost:3306/addressbook_db
spring.datasource.username=root
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver